// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0lY_DpfIEnB4MSKQW0RAZaaxlzC1euu0',
    appId: '1:89745259952:web:123be4029e6c3fd6b4ea75',
    messagingSenderId: '89745259952',
    projectId: 'registrocandadosnettel-6b75a',
    authDomain: 'registrocandadosnettel-6b75a.firebaseapp.com',
    storageBucket: 'registrocandadosnettel-6b75a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh5AkMMNtBmg_VCNQ7EUaGVMwezUGJYb0',
    appId: '1:89745259952:android:35fd0f1b9ea8c0aab4ea75',
    messagingSenderId: '89745259952',
    projectId: 'registrocandadosnettel-6b75a',
    storageBucket: 'registrocandadosnettel-6b75a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7GHXs3zCv0cWioKP54HIQf5SSxgkXGPA',
    appId: '1:89745259952:ios:5d0d1cff4a6778a4b4ea75',
    messagingSenderId: '89745259952',
    projectId: 'registrocandadosnettel-6b75a',
    storageBucket: 'registrocandadosnettel-6b75a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7GHXs3zCv0cWioKP54HIQf5SSxgkXGPA',
    appId: '1:89745259952:ios:5d0d1cff4a6778a4b4ea75',
    messagingSenderId: '89745259952',
    projectId: 'registrocandadosnettel-6b75a',
    storageBucket: 'registrocandadosnettel-6b75a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0lY_DpfIEnB4MSKQW0RAZaaxlzC1euu0',
    appId: '1:89745259952:web:d385cea8d585bad8b4ea75',
    messagingSenderId: '89745259952',
    projectId: 'registrocandadosnettel-6b75a',
    authDomain: 'registrocandadosnettel-6b75a.firebaseapp.com',
    storageBucket: 'registrocandadosnettel-6b75a.firebasestorage.app',
  );
}
